spring:
  application:
    name: dog-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false;MODE=PostgreSQL
    username: sa
    password: sa
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
---
server:
  port: 8100
spring:
  config.activate.on-profile: default
---
server:
  port: 8101
spring:
  config.activate.on-profile: instance2
